name: Build and package CRYPTO_EXTRA plugin

on:
  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: lefred/mariadb-plugin-ci/.github/workflows/build-plugin.yml@main
    with:
      plugin_name: crypto-extra
      plugin_directory: crypto_extra
      build_target: crypto_extra
      plugin_library: crypto_extra.so

      sdk_image: quay.io/lefred14/mariadb-plugin-build
      mariadb_versions: |
          13.0.2
          13.1.1

      extra_packages: libargon2-devel
      cmake_options: -DPLUGIN_CRYPTO_EXTRA=DYNAMIC -DWITH_SSL=system
      test_suite: crypto_extra
      run_tests: false
